# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PokeDex’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeDex
  pod 'MBProgressHUD', '~> 0.9'
  pod 'Alamofire', '~> 3.4'
  pod "Unbox"
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
  pod 'Kingfisher', '~> 2.4'

end
